### PR TITLE
add SANITIZER and STARVED exec result codes

### LINKED ISSUE #12: Needs to be updated to support latest QEMU return values
The following return codes were added to QEMU-Nyx (https://github.com/nyx-fuzz/QEMU-Nyx/blob/fc39d1d5da5221f12b632653cdea7c359346cfd4/nyx/auxiliary_buffer.h#L47-L48) but this library does not support them yet:
- https://github.com/nyx-fuzz/libnyx/blob/acaf7f6346eeb5f1e2cf043543316909fca43650/fuzz_runner/src/nyx/aux_buffer.rs#L16-L21
- https://github.com/nyx-fuzz/libnyx/blob/acaf7f6346eeb5f1e2cf043543316909fca43650/fuzz_runner/src/nyx/qemu_process.rs#L242-L261
- https://github.com/nyx-fuzz/libnyx/blob/acaf7f6346eeb5f1e2cf043543316909fca43650/fuzz_runner/src/nyx/qemu_process.rs#L355-L372
- https://github.com/nyx-fuzz/libnyx/blob/acaf7f6346eeb5f1e2cf043543316909fca43650/libnyx/src/lib.rs#L288-L295

### PR DESCRIPTION
**Pull request by acidghost**
Fixes #12.

Not sure if the associations with `NyxReturnValue` are fine or more variants of it should be added for the new result codes.

### CODE REVIEW

**Comment by schumilo** [comment]
I think it’s fine for now. AFAIK both result codes are only used by Intel's kAFL fork (though the fork doesn't use libnyx yet). But yeah...we should definitely extend `NxyReturnValue` in the future.
Anyway, thanks again for your PR :)

**Comment by acidghost** [comment]
@schumilo actually I got the "starved" result code from QEMU-Nyx, which crashed the fuzzer 😅 . It was recently merged into the main branch from `qemu-nyx-4.2.0-dev-intel` (https://github.com/nyx-fuzz/QEMU-Nyx/pull/10).

**Comment by il-steffen** [comment]
@acidghost the starved result code should only trigger if you provide non-zero argument in the RELEASE hypercall. Did you observe something different?

https://github.com/nyx-fuzz/QEMU-Nyx/pull/10/commits/c12c6bd70db29f59dcf1069b8a3064a90ec4288d#diff-1872baa30d6294198890713430742623fe37ffe1912e9df79c9b76a9746eb1d6

**Comment by il-steffen** [comment]
@schumilo I guess this bit is another candidate for the generic ijon/aux return info buffer

**Comment by acidghost** [comment]
@il-steffen I'm aware of that, but I can trigger the crash reliably on LightFTP (see nyx-fuzz/packer#10) 🤷

**Pull request merged**
