### PR TITLE
Upgrade various dependencies, fixes rustix build error

### PR DESCRIPTION
**Pull request by choller**
This patch upgrades dependencies to resolve a build error with rustix

### CODE REVIEW

**Comment by Wenzel** [comment]
Thanks for the PR @choller 
But I still get a compilation error when trying to build libnyx
image

Any idea what's wrong ?

**Comment by choller** [comment]
> Any idea what's wrong ?

I assume you already tried a cargo clean or this is a new checkout? Can you check what bitflags version is listed in your Cargo.lock?

**Comment by Wenzel** [comment]
I have bitflags `1.2.1`
image

**Comment by choller** [comment]
This should be `1.3.2` instead. You can try adding a dependency for `1.3.2` into Cargo.toml and rerun to see what is pulling in the old version.

**Comment by Wenzel** [comment]
@schumilo ok to merge this ?

**Comment by schumilo** [comment]
Looks good! Thanks!

**Pull request merged**
